### ISSUE TITLE
Hi~how to run the project?

### ISSUE THREAD

**Issue by wangrongding** [zhzhch335/mosaic#1]
![image](https://user-images.githubusercontent.com/42437658/127446659-930a1ea3-86bc-47a5-9e55-fa2550a23159.png)
![image](https://user-images.githubusercontent.com/42437658/127446685-028c67f4-7d26-4838-9b5e-73d0270550be.png)

**Comment by zhzhch335** [comment]
我晚上回去写个readme
基本上就是分两步运行的
第一步先跑index_getDiff.js计算每个图片和主图各个像素的差值
第二步再跑index.js 进行拼图并输出各个块的位置的json文件

**Comment by wangrongding** [comment]
好的,十分感谢~🦄

**Comment by zhzhch335** [comment]
写好啦
