### ISSUE TITLE
作者你好,有个疑问想问一下您

### ISSUE THREAD

**Issue by wangrongding** [zhzhch335/mosaic#2]
我最近也在做这个千图成像玩,
在计算图片和一个范围的像素块的颜色差值是通过欧氏距离求的,
这点应该没有问题,但是最后生成的图像并没有和想象中的一样很好的匹配上,
我想问题应该出在求两个目标的主色调上,您是通过取它的最多出现的颜色,还是所有颜色的平均值作为用来对比的主色调呢
在这个地方卡壳了,希望能得到您的指点,谢谢!

**Comment by zhzhch335** [comment]
为了避免混淆 我们称呼大图为A 一堆小图为B
首先将A按照自己的需求像素化(我的例子中是处理成25*25共625个像素点） 得到625个小a
然后将每个小图B分别计算与这625个小a的颜色差值
你说的应该是这一步吧
这一步的做法我是继续将小图B进行像素化（具体用了多少我忘了，可能是30*30）得到小b，然后这900个小b与每个小a计算颜色差值然后**取平均数**（也就是说最终得到625个数字代表B分别与A的每一个像素点小a的差值），由于这一步是计算完之后直接求平均值的，B的像素数值增大（也就是小b的数量增多）不会引起计算量的指数提升，所以多写一点没啥问题

**Comment by wangrongding** [comment]
> 为了避免混淆 我们称呼大图为A 一堆小图为B
> 首先将A按照自己的需求像素化(我的例子中是处理成25_25共625个像素点） 得到625个小a 然后将每个小图B分别计算与这625个小a的颜色差值 你说的应该是这一步吧 这一步的做法我是继续将小图B进行像素化（具体用了多少我忘了，可能是30_30）得到小b，然后这900个小b与每个小a计算颜色差值然后**取平均数**（也就是说最终得到625个数字代表B分别与A的每一个像素点小a的差值），由于这一步是计算完之后直接求平均值的，B的像素数值增大（也就是小b的数量增多）不会引起计算量的指数提升，所以多写一点没啥问题

受教了💗我的处理方法和您的差不多,
这是我的实践项目,
https://github.com/wangrongding/love-collection
